[package]
name = "leetcode"
version = "0.1.0"
authors = ["CNife <CNife@vip.qq.com>"]
edition = "2018"

[workspace]
members = ["finished", "helper", "utils"]

[dependencies.utils]
version = "^0.1.0"
path = "./utils"
